#!/bin/bash

# create database
createdb -l C -E UTF-8 -T template0 -O musicbrainz musicbrainz

# lang?
createlang plpgsql musicbrainz

# do rest of automated stuff
set -xv

# change to scripts subdir
cd mbslave2

echo 'CREATE SCHEMA musicbrainz;' | ./mbslave-psql.py -S
echo 'CREATE SCHEMA statistics;' | ./mbslave-psql.py -S
echo 'CREATE SCHEMA cover_art_archive;' | ./mbslave-psql.py -S

./mbslave-remap-schema.py <sql/CreateTables.sql | sed 's/CUBE/TEXT/' | ./mbslave-psql.py
./mbslave-remap-schema.py <sql/statistics/CreateTables.sql | ./mbslave-psql.py
./mbslave-remap-schema.py <sql/caa/CreateTables.sql | ./mbslave-psql.py

# import data dumps from volume
./mbslave-import.py \
	/dumps/mbdump.tar.bz2 \
	/dumps/mbdump-derived.tar.bz2 \
	/dumps/mbdump-cdstubs.tar.bz2 \
	/dumps/mbdump-cover-art-archive.tar.bz2

# create keys and indexes
./mbslave-remap-schema.py <sql/CreatePrimaryKeys.sql | ./mbslave-psql.py
./mbslave-remap-schema.py <sql/statistics/CreatePrimaryKeys.sql | ./mbslave-psql.py
./mbslave-remap-schema.py <sql/caa/CreatePrimaryKeys.sql | ./mbslave-psql.py
./mbslave-remap-schema.py <sql/wikidocs/CreatePrimaryKeys.sql | ./mbslave-psql.py
./mbslave-remap-schema.py <sql/documentation/CreatePrimaryKeys.sql | ./mbslave-psql.py

# now come the indexes we care about
./mbslave-remap-schema.py <sql/CreateIndexes.sql | grep -vE '(collate|medium_index)' | ./mbslave-psql.py
./mbslave-remap-schema.py <sql/CreateSlaveIndexes.sql | ./mbslave-psql.py
./mbslave-remap-schema.py <sql/statistics/CreateIndexes.sql | ./mbslave-psql.py
./mbslave-remap-schema.py <sql/caa/CreateIndexes.sql | ./mbslave-psql.py

./mbslave-remap-schema.py <sql/CreateViews.sql | ./mbslave-psql.py

# upgrade
./mbslave-remap-schema.py <sql/updates/schema-change/22.slave_only.sql | ./mbslave-psql.py
./mbslave-remap-schema.py <sql/updates/schema-change/22.slave.sql | grep -v to_tsvector | ./mbslave-psql.py
echo 'UPDATE replication_control SET current_schema_sequence = 22;' | ./mbslave-psql.py

# vacuum
echo 'VACUUM ANALYZE;' | ./mbslave-psql.py